### ISSUE TITLE
Cesium.js sample outputs error on console

### ISSUE THREAD

**Issue by cx20** [cx20/gltf-test#603]
When I try to display the sample below, an error is output to the console.
https://cx20.github.io/gltf-test/examples/cesium/index.html?model=Duck

```
cesiumWorkerBootstrapper.js:6 
Uncaught Error: importScripts failed for Workers/createVerticesFromHeightmap at https://cx20.github.io/gltf-test/libs/cesium/1.95/Workers/createVerticesFromHeightmap.js
http://requirejs.org/docs/errors.html#importscripts
    at makeError (cesiumWorkerBootstrapper.js:6:1960)
    at req.load (cesiumWorkerBootstrapper.js:6:4053)
    at Object.load (cesiumWorkerBootstrapper.js:6:16653)
    at i.load (cesiumWorkerBootstrapper.js:6:10213)
    at i.fetch (cesiumWorkerBootstrapper.js:6:10012)
    at i.check (cesiumWorkerBootstrapper.js:6:11218)
    at i.enable (cesiumWorkerBootstrapper.js:6:13311)
    at Object.enable (cesiumWorkerBootstrapper.js:6:15766)
    at i.<anonymous> (cesiumWorkerBootstrapper.js:6:13165)
    at cesiumWorkerBootstrapper.js:6:1705
```

**Comment by javagl** [comment]
This might just have been a glitch - at least, it seems to work for me...
If this is still an issue, consider dropping a short note here or opening an issue in https://github.com/CesiumGS/cesium

**Comment by cx20** [comment]
Thank you for the info. I've confirmed that the error has been resolved.

**Comment by javagl** [comment]
I hope that it's OK to drop that random remark here: This repo is an invaluable resource for tracking the status and conformance of glTF viewer implementations. I (and probably the whole community) appreciate all the work is that you are putting into this 👍
